export const titleOfPage = "Form Data"
export const descriptionOfPage = "Upload Form Data"
export const scriptUrlForAppsScript = "https://script.google.com/macros/s/AKfycbxFFOGC5AJIMA4AKmhcONW7wtOqL7nl82JNcmQ-l6abyEfxtdq61XkSysWtcNGBcww/exec"
export const folderIdOfDrive = "1oR3Iksj5iyPTeubj6oAqUgY_-LhyokBi"
export const apiUrl = "https://sepia-disco-block.glitch.me"
// export const apiUrl = "https://engineerresumereview.xyz:5001"
export const titleOfSeoForFormData = "Form Data"
export const descriptionOfSeoForFormData = "Upload Your Files"
export const nameOfSeoForFormData = "Form Data"
export const typeOfSeoForFormData = "website"
export const mainTitleSeoForFormData = "Fill the Form and Upload File"
export const subtitleSeoForFormData = "Upload Your Files"
export const contentOfSubtitleSeoForFormData = "You can upload any file whichever you want"
export const hrefSeoForFormData = "/from-data"
export const imageSeoForFormData = "%PUBLIC_URL%/formdata-icon.png"
export const urlSeoForFormData = "%PUBLIC_URL%"

